---
title: "HCI:<br>Conceptual Design"
author: Mick McQuaid
date: today
bibliography: master.bib
format:
  revealjs:
    logo: iSchoolLogo.png
    theme: moon
    css: style.css
    transition: slide
    background-transition: fade
    preview-links: auto
    controls: true
    controls-layout: bottom-right
    center: true
---

::: {.r-fit-text}
Week SEVEN
:::

# Today

- Guest Speaker / Discussant, Erica Braverman
- Q and A from last time
- Discussion leading (skipped)
- Design Critique (skipped)
- Article Presentation (Ananya Gubbi Mohanbabu)
- Conceptual Design Exercises
- Figma Exercise

# Q and A from last time

## Learning

##
As for the user research part, I find it necessary to reflect on my user interviews. For example, in milestone 2, I looked back at my interview notes and found that at many points, I should have asked users multiple whys, so that I might have unearthed users' secret thoughts and values. But at that time, I thought the answer was expected and did not need to be explained, or I was just busy pushing the interview process.

##
The Figma tutorial was very informative, thank you Rachel!!

##
The Austin History Museum certainly had a cumbersome website that is difficult for users to navigate through. While there were interesting discussions about using library jargons, having no funding to focus on website designs, and having a lot of information to showcase on the website, I think this generally extends to all government websites. Education, weather, taxes, visa appointment websites are all information heavy and have poor information architecture and system design.

##
I really liked the whole auto-animation tutorial we did in Figma today. It was really exciting, and I'd wanted to do it for a long time. I finally had the opportunity to do it in today's class, which was very rewarding. I was so eager to complete it that I found myself trying to guess what Rachel would do next by working ahead and finding myself making mistakes, but I eventually learned from Rachel's way and enjoyed the process. I'm excited to see what else I learn about components in Figma.

##
The sketches are really important factor that play a role in designing. however, funding would play a major role in the drive for innovation, improvement, and implementation.

##
I am looking forward to learning more about sketching from those sketching resources.

To me sketching is like note taking. I feel like it isn't entirely understood by others until it's refined.

Kinda like when you go for an interview and you're taking note, I don't think anyone who isn't you truly understands everything you've written in that preliminary phase.

My categorization would be sketching, lofi prototypes then hifi.

##
Multiple people should contribute to affinity diagramming for a collective process of "clumping and bubbling up" insights.  And the fact that insight comes from the stories of users so interviews potentially more insightful.

##
Being a good interviewer is a skill. This is the art of extracting not just a abundance information, but an abundance of good, useful information that can be synthesized. Everyone has a story to tell during an interview. If the interviewer give them too much, or not enough freedom, we lose that part of the story. It depends on the person being interviewed as well. An example is that in a study, they found that some autistic people feel uncomfortable from small talk. A good interviewer will need to know how to read the person, and adjust their methods accordingly.

## QandA

##
How do we find the focus of design after building the WAAD, rather than trying to cover everything or over-investing in details?

*My view is that the affinity diagramming process leads to a high level view, allowing you to ignore the affinity notes.*

##
No questions for now! Thank you for a very informative class!

*Thank you for a very informative class!*

##
We discussed that continuous innovation and development is necessary and is inevitable. I wonder if there are any design and sketching techniques from the 60s that have changed over time. Since we are still talking about books that were written then, I think this is contradictory to the former point.

*Great point! There are new techniques, but we still study very old ones.*

##
N/A

*Okay*

##
How can the iterative nature of Affinity Diagramming be leveraged to not only organize and categorize ideas but also to uncover underlying insights, patterns, and connections that may not be immediately apparent, for more effective solutions?

*That is the human part of the process that is difficult for LLMs to replicate!*

##
I found the concept of emotion and beauty in UX design as interesting because I enjoyed Don Norman's book. I was curious about the place of beauty and emotion in design, and how that fits into an information-driven program such as our own here at the iSchool.

*Schiller and Goethe argued about which is more important, beauty or truth. It's a worthwhile argument!*

##
You didn't say what we shouldn't take notes about during an interview.

*Good point! Hard to know what will prove irrelevant to the task at hand! Requires interview experience and reflection!*

##
How do you know when you have enough insights to move from affinity mapping to prototyping?

*You don't, in my view! You move from affinity diagramming to personas to storyboard and then prototyping!*

How might the sketching/interpretation process be adapted for digital tools vs analog sketchbooks?

*Some people do okay with iPads, but digital whiteboards have mostly been a flop.*

##
Given that producing and organizing affinity notes is a huge resource and labor sink, what is your thoughts on letting an AI categorize the insights, and letting all of the different processes bubble together that way?

*We need to give it a try---my guess is that it will leave out the magic, but hard to tell without experience.*

# Conceptual Design
Instead of droning on about this topic, I'd like to do the exercises in the chapters. In particular, let's do three storyboards, one for each perspective (emotional, interaction, and ecological) as described in Exercise 17-2 on pages 371--372. Let's take an hour to do this, so about fifteen minutes per sketch, with a short break after each one to share with the other group.

# Readings

Readings last week include @Hartson2019: Ch 12, 13, 14

Readings this week include @Hartson2019: Ch 15, 16, 17, @Norman2013: Ch 3, 4

# Assignments
none

# References

::: {#refs}
:::

---

::: {.r-fit-text}
END
:::

# Colophon

This slideshow was produced using `quarto`

Fonts are *League Gothic* and *Lato*

