project:
  type: book

book:
  title: "Welcome to the Command Line"
  author: "Mick McQuaid"
  date: today
  chapters:
    - index.qmd
    - macSetupIntelFull.qmd
    - macSetupIntelMinimal.qmd
    - macSetupM1Full.qmd
    - macSetupM1Minimal.qmd
    - whyCLI.qmd
    - whyVIM.qmd
    - unixNature.qmd
    - man.qmd
    - terminal.qmd
    - macGeneral/iTerm.qmd
    - bash.qmd
    - tmux.qmd
    - bearings.qmd
    - fileIO.qmd
    - fileManipulation.qmd
    - textManipulation.qmd
    - vim.qmd
    - macGeneral/macDotFiles.qmd
    - macGeneral/macVim.qmd
    - references.qmd
format:
  html:
    include-in-header:
     text: |
        <style>
        #quarto-sidebar .menu-text {
          display: flex;
        }
        #quarto-sidebar .chapter-number {
          display: block;
          width: 2rem;
          text-align: right;
          padding-right: 2px;
        }
        #quarto-sidebar .chapter-title {
          display: block;
          padding-left: 8px;
          text-indent: -2px;
          width: 100%;
        }
        </style>
    theme: cosmo
bibliography: master.bib
mainfont: Tex Gyre Schola
monofont: JetBrainsMono Nerd Font
mathfont: Tex Gyre Schola Math

