---
title: "Rapid Prototyping:<br>Individual Course Project"
author: Mick McQuaid
date: 2022-12-01
bibliography: master.bib
format:
  revealjs:
    logo: iSchoolLogo.png
    theme: moon
    css: style.css
    transition: slide
    background-transition: fade
    preview-links: auto
    controls: true
    controls-layout: bottom-right
    center: true
---

::: {.r-fit-text}
Week FOURTEEN
:::

# What it is
This app explores a resource that consists of metadata
about books. It can answer questions like "How many
celebrities published autobiographies over the years
1820 to 1870?"

*How should you answer such questions?*

# What it is not
It is not a way to search for a book to read.

# What problems can you solve?

## Browsing
- How can you help the user understand what is available at a glance?
- How can you represent questions?
- Can you help the user formulate questions?
- What kinds of graphics can best represent answers to questions?

## Updating
The author column of the original table has misspellings
and variant spellings. What could you do about that?

Hint: autocompletion or dropdown leads to fewer errors than freeform
entry. A dialog showing variant spellings may be
helpful. When would you present that?

Note that searching for variant titles or authors takes
time. What does the user see in that time?

# Talent
*In your choice lies your talent.* (This was a popular
maxim of the actress Stella Adler.)

Your rationale for your choice reveals a great deal that
is not obvious to the casual observer.

# My job
I have to render a subjective judgment about your work
in which I try to represent *good taste* as it is popularly
defined in our era. To some extent I have prejudices and
inherit prejudices of our era. Some of you may be ahead
of your time and some may be behind the times. I have to
manage my expectations of your work with that in mind.

# Now
Please share any work that you have done so far for which you would like feedback.

---

::: {.r-fit-text}
END
:::

# Colophon

This slideshow was produced using `quarto`

Fonts are *League Gothic* and *Lato*

<!--
vim:filetype=pandoc
-->
