
## Install basic brew packages
This installation process is tedious but informative. If you prefer, there is a utility file in Canvas > Files > misc > basicBrewPackages.sh that does all of these at once. Beware, though, that you may miss important messages that way.

```bash
brew install python # keeps Python more up-to-date than native macOS python
pip3 install powerline-status # gives a better command prompt
brew install coreutils # replaces basic cli utilities with enhanced versions
brew install findutils # enhancements for the Unix find utility
brew install ruby # installs a more recent version of ruby than the native macOS version
gem install colorls # gives color-coded filenames when invoking ls
gem install github-pages # utilities for website building
brew install tmux # a terminal multiplexer
brew install rename # simplifies pattern renaming of files
brew install macvim # both gui and cli version of the vim editor
brew install pandoc # converts documents between platforms such as qmd, pdf, html, docx, epub, and more
pip3 install pandoc-include # enables including markdown documents in other markdown documents (not for Quarto, just plain markdown)
brew install pandoc-include-code # enables including program files in markdown documents (not for Quarto, just plain markdown)
brew install quarto # scientific document and presentation system
brew install trash # enables a command line trash function
brew install clipy # improves clipboard management
brew install saulpw/vd/visidata # cli csv file manager
brew install gnu-tar # improved archive management
brew install grep # improved regular expression search
brew install bib-tool # manages bibliography files created with bibtex or biblatex
brew install font-tex-gyre-schola # font used by quarto
brew install font-tex-gyre-schola-math # font used by quarto
brew install font-jetbrains-mono-nerd-font # font used by quarto
```

Most of these installations also install a `man` page or at least a help file. For example, you can say

```bash
man trash
```

to get information about the `trash` utility. The `man` pages have a specialized, hard-to-grasp format if you're new to them, so you may want to check out the `man` module before making extensive use of them.

For those programs that have no `man` page, you can usually say `<name of command> --help` to get a help page. For instance, you can say

```bash
quarto --help
```

to get some brief help for using the cli version of Quarto. Of course, Quarto also has a web page at [https://quarto.org/](https://quarto.org/) that gives *much* more information about it.

