
## Check and Update Apple ID
This helps with warranty repair and sharing among multiple Apple devices. It should be the first item in the list under  > System Settings...

## Open Finder
  Go to Settings > Advanced > Show all file extensions

## Open System Settings
This is the first menu item on the Apple () menu.

- keyboard > keyboard shortcuts > modifier keys > change caps-lock to ctrl
- desktop and dock > automatically hide and show the dock
- desktop and dock > automatically hide and show menubar on desktop (if no notch)
- desktop and dock > change Magnification to Large
- trackpad > More gestures > Swipe between pages > three fingers

## Install XCode
Do this from the macOS app store, which is the third menu item under the Apple () menu.

Installation takes a million years! Make sure you have some time or can leave the computer running.

Be sure to open XCode after install to initialize and possibly to install command line utilities. (It used to make you install command line utilities but I already did that so I can't tell if the current version is not making me do it because I have it installed or because it's no longer required.)

